steps:
  - id: 'Instalando aplicativo GO...'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', 'sum']
    env: ['GOPATH=.']

  - id: 'Executando Testes...'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v','./...']
    env: ['GOPATH=.']